name: Build and Deploy Spring App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Build Application
        run: mvn -f pom.xml clean package

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v4
        with:
            name: artifact
            path: ./target/cicd-0.0.1-SNAPSHOT.jar


